[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700
username=supervisor
password=supervisor

[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
username=supervisor
password=supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:api]
command=/app/api
directory=/app
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=KLEIN_SNOWFLAKE_NODE_ID="1",KLEIN_LOGGER_CONSOLE="true"

[program:admin]
command=/app/admin
directory=/app
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=KLEIN_SNOWFLAKE_NODE_ID="2",KLEIN_LOGGER_CONSOLE="true"

[program:openai]
command=/app/openai
directory=/app
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=KLEIN_SNOWFLAKE_NODE_ID="3",KLEIN_SERVER_OPENAI_HOST="127.0.0.1",KLEIN_SERVER_OPENAI_PORT="17201",KLEIN_LOGGER_CONSOLE="true"

[program:worker]
command=/app/worker
directory=/app
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=KLEIN_SNOWFLAKE_NODE_ID="4",KLEIN_LOGGER_CONSOLE="true"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
directory=/
autostart=true
autorestart=true
startsecs=1
stopsignal=QUIT
stopwaitsecs=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
